FROM node:16-alpine AS builder
ENV NODE_ENV production

WORKDIR /usr/src/app

COPY package*.json .
COPY yarn.lock .
RUN yarn install --production

COPY . .

RUN yarn build


FROM node:16-alpine AS production

COPY --from=builder /usr/src/app/build.js .

EXPOSE 4000
CMD [ "node", "build.js" ]