apiVersion: v1
kind: Service
metadata:
  name: sequence-web-back
  labels:
    app: web
spec:
    selector:
    ports:
      - name: mongo 
        protocol: "TCP"
        port: 27017
        targetPort: 27017
      - name : sqc-back
        protocol: "TCP"
        port: 8879
        targetPort: 8879